# Generated by Django 3.2.23 on 2023-11-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_auto_20231107_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
    ]
